max-line-length: 120
ignore-paths:
    - InteractiveCoursera
    - IndustrialProgramming/advanced
    - IndustrialProgramming/basics
    - IndustrialProgramming/classes
    - IndustrialProgramming/extra
    - IndustrialProgramming/data                                          
